services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: zappgo-be
    container_name: zappgo-be
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file:
      - .env
